# No more than 2 GPU tasks can run at once + a few jobs for other tasks
jobs: 8
#
slurm: true
use-envmodules: true
resources:
  # Queue at most 3 GPU-using tasks on the GPU node
  - "gputask=3"
  # Queue at most 2 misc tasks on the GPU node
  - "gpumisc=2"
default-resources:
  - "mem_mb=None"
max-jobs-per-second: 5
max-status-checks-per-second: 4
local-cores: 16
latency-wait: 60
rerun-incomplete: True
scheduler: greedy
