# No more than 2 GPU tasks can run at once + a few jobs for other tasks
jobs: 16
#
slurm: true
use-envmodules: true
resources:
  # Queue at most 3 GPU-using tasks on the GPU node
  - "gputask=3"
  # Queue at most 2 misc tasks on the GPU node
  - "gpumisc=2"
default-resources:
   # Same mem-per-CPU as server defaults, to silence warning
  - "mem_mb_per_cpu=15948"
  # High runtime limit, to catch jobs that hang
  - "runtime=720"
max-jobs-per-second: 5
max-status-checks-per-second: 4
local-cores: 16
latency-wait: 60
rerun-incomplete: True
scheduler: greedy
