# Location of raw FAST5 files organized by sample
input_dir: "data"
# Destination for pipeline output
results_dir: "output"

# Number of fast5 files per batch
batch_size: 90

# Number of reads sampled for detailed QC reports
qc_sample: 1000000

# Location of reference genome (FASTA) used by minimap (REQUIRED)
# minimap2_fasta: "path/to/genome.fasta"

# Tandem repeats file for sniffles; must be a path, null, or an empty string
sniffles_tandem_repeats:

# List of sample to exclude from genotyping
excluded_from_genotyping: []
