# Location of raw FAST5 files organized by sample
input_dir: "data"
# Destination for pipeline output
results_dir: "output"

# Number of fast5 files per batch
batch_size: 25

# Location of dorado basecalling model
dorado_model: "/opt/software/dorado/0.2.4/models/dna_r9.4.1_e8_sup@v3.3"

# Location of reference genome (FASTA) used by minimap
minimap2_fasta: "resources/Homo_sapiens.GRCh38_full_analysis_set_plus_decoy_hla_noColonsAsterisks.fa"
